// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAGiiYaOh8SifGAwBLueG9-7S6vjIr9YAc',
    appId: '1:394644892502:web:9b4996ea605620d55e04f7',
    messagingSenderId: '394644892502',
    projectId: 'app-repartidor-prog-movil2025',
    authDomain: 'app-repartidor-prog-movil2025.firebaseapp.com',
    storageBucket: 'app-repartidor-prog-movil2025.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDA1vC7C5qzN8fhRxrnfBMk3k2hXTLbKcM',
    appId: '1:394644892502:android:15e2ab652df5ac8d5e04f7',
    messagingSenderId: '394644892502',
    projectId: 'app-repartidor-prog-movil2025',
    storageBucket: 'app-repartidor-prog-movil2025.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAGiiYaOh8SifGAwBLueG9-7S6vjIr9YAc',
    appId: '1:394644892502:web:fa1c7b739e397c5f5e04f7',
    messagingSenderId: '394644892502',
    projectId: 'app-repartidor-prog-movil2025',
    authDomain: 'app-repartidor-prog-movil2025.firebaseapp.com',
    storageBucket: 'app-repartidor-prog-movil2025.firebasestorage.app',
  );
}
